"""


"""
from __future__ import annotations

# Import:
from typing import Final
from jgdv.debugging import TraceBuilder

##--| Error Messages
ErrorMSg_1 : Final[str] = "Test Message"


##--| Error Classes
class CustomError(Exception):
    """ The Base Error type that Strang's raise """

    def __getitem__(self, val:None|int|slice) -> Self:
        """ Use jgdv.debugging.TraceBuilder to control the traceback
        of this error

        """
        match val:
            case int() as x:
                return self.with_traceback(TraceBuilder()[x])
            case slice(start=None) as x:
                adjusted = slice(1, x.stop, x.step)
                return self.with_traceback(TraceBuilder()[adjusted])
            case slice(start=int() as start) as x:
                adjusted = slice(1+start, x.stop, x.step)
                return self.with_traceback(TraceBuilder()[adjusted])
            case None:
                return self.with_traceback(TraceBuilder()[1:])